stages:
  - test
  - build

variables:
  GO_VERSION: "1.23"  # Укажите нужную версию Go
  BIN_NAME: "app"   # Имя бинарного файла
  ARTIFACTS_DIR: "artifacts"

# Используем Docker образ с нужной версией Go
image: golang:${GO_VERSION}-alpine

before_script:
  - mkdir -p ${ARTIFACTS_DIR}
  - go version
  - go env

unit-tests:
  stage: test
  script:
    - go test -v -race -coverprofile=${ARTIFACTS_DIR}/coverage.out ./...
    - go tool cover -func=${ARTIFACTS_DIR}/coverage.out
  artifacts:
    paths:
      - ${ARTIFACTS_DIR}/coverage.out
    expire_in: 1 week

build:
  stage: build
  script:
    - CGO_ENABLED=0 go build -v -o ${ARTIFACTS_DIR}/${BIN_NAME} .
    - ./${ARTIFACTS_DIR}/${BIN_NAME} --version  # Проверяем что бинарник запускается
  artifacts:
    paths:
      - ${ARTIFACTS_DIR}/${BIN_NAME}
    expire_in: 1 week