version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
