version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: ./infra/docker/Dockerfile
    ports:
      - "8081:8081"
    restart: always
    environment:
      CONFIG_FILE: /app/configs/values_local.yaml

  master:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    name: data