// Code generated by http://github.com/gojuno/minimock (v3.4.0). DO NOT EDIT.

package handlers

//go:generate minimock -i screen-time-limiter/internal/app/handlers.userRepo -o user_repo_mock_test.go -n UserRepoMock -p handlers

import (
	"context"
	"screen-time-limiter/internal/domain/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UserRepoMock implements userRepo
type UserRepoMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAdd          func(ctx context.Context, user model.User) (err error)
	funcAddOrigin    string
	inspectFuncAdd   func(ctx context.Context, user model.User)
	afterAddCounter  uint64
	beforeAddCounter uint64
	AddMock          mUserRepoMockAdd
}

// NewUserRepoMock returns a mock for userRepo
func NewUserRepoMock(t minimock.Tester) *UserRepoMock {
	m := &UserRepoMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddMock = mUserRepoMockAdd{mock: m}
	m.AddMock.callArgs = []*UserRepoMockAddParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUserRepoMockAdd struct {
	optional           bool
	mock               *UserRepoMock
	defaultExpectation *UserRepoMockAddExpectation
	expectations       []*UserRepoMockAddExpectation

	callArgs []*UserRepoMockAddParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserRepoMockAddExpectation specifies expectation struct of the userRepo.Add
type UserRepoMockAddExpectation struct {
	mock               *UserRepoMock
	params             *UserRepoMockAddParams
	paramPtrs          *UserRepoMockAddParamPtrs
	expectationOrigins UserRepoMockAddExpectationOrigins
	results            *UserRepoMockAddResults
	returnOrigin       string
	Counter            uint64
}

// UserRepoMockAddParams contains parameters of the userRepo.Add
type UserRepoMockAddParams struct {
	ctx  context.Context
	user model.User
}

// UserRepoMockAddParamPtrs contains pointers to parameters of the userRepo.Add
type UserRepoMockAddParamPtrs struct {
	ctx  *context.Context
	user *model.User
}

// UserRepoMockAddResults contains results of the userRepo.Add
type UserRepoMockAddResults struct {
	err error
}

// UserRepoMockAddOrigins contains origins of expectations of the userRepo.Add
type UserRepoMockAddExpectationOrigins struct {
	origin     string
	originCtx  string
	originUser string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAdd *mUserRepoMockAdd) Optional() *mUserRepoMockAdd {
	mmAdd.optional = true
	return mmAdd
}

// Expect sets up expected params for userRepo.Add
func (mmAdd *mUserRepoMockAdd) Expect(ctx context.Context, user model.User) *mUserRepoMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("UserRepoMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &UserRepoMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.paramPtrs != nil {
		mmAdd.mock.t.Fatalf("UserRepoMock.Add mock is already set by ExpectParams functions")
	}

	mmAdd.defaultExpectation.params = &UserRepoMockAddParams{ctx, user}
	mmAdd.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAdd.expectations {
		if minimock.Equal(e.params, mmAdd.defaultExpectation.params) {
			mmAdd.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAdd.defaultExpectation.params)
		}
	}

	return mmAdd
}

// ExpectCtxParam1 sets up expected param ctx for userRepo.Add
func (mmAdd *mUserRepoMockAdd) ExpectCtxParam1(ctx context.Context) *mUserRepoMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("UserRepoMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &UserRepoMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.params != nil {
		mmAdd.mock.t.Fatalf("UserRepoMock.Add mock is already set by Expect")
	}

	if mmAdd.defaultExpectation.paramPtrs == nil {
		mmAdd.defaultExpectation.paramPtrs = &UserRepoMockAddParamPtrs{}
	}
	mmAdd.defaultExpectation.paramPtrs.ctx = &ctx
	mmAdd.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmAdd
}

// ExpectUserParam2 sets up expected param user for userRepo.Add
func (mmAdd *mUserRepoMockAdd) ExpectUserParam2(user model.User) *mUserRepoMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("UserRepoMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &UserRepoMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.params != nil {
		mmAdd.mock.t.Fatalf("UserRepoMock.Add mock is already set by Expect")
	}

	if mmAdd.defaultExpectation.paramPtrs == nil {
		mmAdd.defaultExpectation.paramPtrs = &UserRepoMockAddParamPtrs{}
	}
	mmAdd.defaultExpectation.paramPtrs.user = &user
	mmAdd.defaultExpectation.expectationOrigins.originUser = minimock.CallerInfo(1)

	return mmAdd
}

// Inspect accepts an inspector function that has same arguments as the userRepo.Add
func (mmAdd *mUserRepoMockAdd) Inspect(f func(ctx context.Context, user model.User)) *mUserRepoMockAdd {
	if mmAdd.mock.inspectFuncAdd != nil {
		mmAdd.mock.t.Fatalf("Inspect function is already set for UserRepoMock.Add")
	}

	mmAdd.mock.inspectFuncAdd = f

	return mmAdd
}

// Return sets up results that will be returned by userRepo.Add
func (mmAdd *mUserRepoMockAdd) Return(err error) *UserRepoMock {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("UserRepoMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &UserRepoMockAddExpectation{mock: mmAdd.mock}
	}
	mmAdd.defaultExpectation.results = &UserRepoMockAddResults{err}
	mmAdd.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAdd.mock
}

// Set uses given function f to mock the userRepo.Add method
func (mmAdd *mUserRepoMockAdd) Set(f func(ctx context.Context, user model.User) (err error)) *UserRepoMock {
	if mmAdd.defaultExpectation != nil {
		mmAdd.mock.t.Fatalf("Default expectation is already set for the userRepo.Add method")
	}

	if len(mmAdd.expectations) > 0 {
		mmAdd.mock.t.Fatalf("Some expectations are already set for the userRepo.Add method")
	}

	mmAdd.mock.funcAdd = f
	mmAdd.mock.funcAddOrigin = minimock.CallerInfo(1)
	return mmAdd.mock
}

// When sets expectation for the userRepo.Add which will trigger the result defined by the following
// Then helper
func (mmAdd *mUserRepoMockAdd) When(ctx context.Context, user model.User) *UserRepoMockAddExpectation {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("UserRepoMock.Add mock is already set by Set")
	}

	expectation := &UserRepoMockAddExpectation{
		mock:               mmAdd.mock,
		params:             &UserRepoMockAddParams{ctx, user},
		expectationOrigins: UserRepoMockAddExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAdd.expectations = append(mmAdd.expectations, expectation)
	return expectation
}

// Then sets up userRepo.Add return parameters for the expectation previously defined by the When method
func (e *UserRepoMockAddExpectation) Then(err error) *UserRepoMock {
	e.results = &UserRepoMockAddResults{err}
	return e.mock
}

// Times sets number of times userRepo.Add should be invoked
func (mmAdd *mUserRepoMockAdd) Times(n uint64) *mUserRepoMockAdd {
	if n == 0 {
		mmAdd.mock.t.Fatalf("Times of UserRepoMock.Add mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAdd.expectedInvocations, n)
	mmAdd.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAdd
}

func (mmAdd *mUserRepoMockAdd) invocationsDone() bool {
	if len(mmAdd.expectations) == 0 && mmAdd.defaultExpectation == nil && mmAdd.mock.funcAdd == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAdd.mock.afterAddCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAdd.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Add implements userRepo
func (mmAdd *UserRepoMock) Add(ctx context.Context, user model.User) (err error) {
	mm_atomic.AddUint64(&mmAdd.beforeAddCounter, 1)
	defer mm_atomic.AddUint64(&mmAdd.afterAddCounter, 1)

	mmAdd.t.Helper()

	if mmAdd.inspectFuncAdd != nil {
		mmAdd.inspectFuncAdd(ctx, user)
	}

	mm_params := UserRepoMockAddParams{ctx, user}

	// Record call args
	mmAdd.AddMock.mutex.Lock()
	mmAdd.AddMock.callArgs = append(mmAdd.AddMock.callArgs, &mm_params)
	mmAdd.AddMock.mutex.Unlock()

	for _, e := range mmAdd.AddMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAdd.AddMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAdd.AddMock.defaultExpectation.Counter, 1)
		mm_want := mmAdd.AddMock.defaultExpectation.params
		mm_want_ptrs := mmAdd.AddMock.defaultExpectation.paramPtrs

		mm_got := UserRepoMockAddParams{ctx, user}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmAdd.t.Errorf("UserRepoMock.Add got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAdd.AddMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.user != nil && !minimock.Equal(*mm_want_ptrs.user, mm_got.user) {
				mmAdd.t.Errorf("UserRepoMock.Add got unexpected parameter user, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAdd.AddMock.defaultExpectation.expectationOrigins.originUser, *mm_want_ptrs.user, mm_got.user, minimock.Diff(*mm_want_ptrs.user, mm_got.user))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAdd.t.Errorf("UserRepoMock.Add got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAdd.AddMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAdd.AddMock.defaultExpectation.results
		if mm_results == nil {
			mmAdd.t.Fatal("No results are set for the UserRepoMock.Add")
		}
		return (*mm_results).err
	}
	if mmAdd.funcAdd != nil {
		return mmAdd.funcAdd(ctx, user)
	}
	mmAdd.t.Fatalf("Unexpected call to UserRepoMock.Add. %v %v", ctx, user)
	return
}

// AddAfterCounter returns a count of finished UserRepoMock.Add invocations
func (mmAdd *UserRepoMock) AddAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.afterAddCounter)
}

// AddBeforeCounter returns a count of UserRepoMock.Add invocations
func (mmAdd *UserRepoMock) AddBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.beforeAddCounter)
}

// Calls returns a list of arguments used in each call to UserRepoMock.Add.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAdd *mUserRepoMockAdd) Calls() []*UserRepoMockAddParams {
	mmAdd.mutex.RLock()

	argCopy := make([]*UserRepoMockAddParams, len(mmAdd.callArgs))
	copy(argCopy, mmAdd.callArgs)

	mmAdd.mutex.RUnlock()

	return argCopy
}

// MinimockAddDone returns true if the count of the Add invocations corresponds
// the number of defined expectations
func (m *UserRepoMock) MinimockAddDone() bool {
	if m.AddMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddMock.invocationsDone()
}

// MinimockAddInspect logs each unmet expectation
func (m *UserRepoMock) MinimockAddInspect() {
	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepoMock.Add at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddCounter := mm_atomic.LoadUint64(&m.afterAddCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddMock.defaultExpectation != nil && afterAddCounter < 1 {
		if m.AddMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserRepoMock.Add at\n%s", m.AddMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserRepoMock.Add at\n%s with params: %#v", m.AddMock.defaultExpectation.expectationOrigins.origin, *m.AddMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAdd != nil && afterAddCounter < 1 {
		m.t.Errorf("Expected call to UserRepoMock.Add at\n%s", m.funcAddOrigin)
	}

	if !m.AddMock.invocationsDone() && afterAddCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepoMock.Add at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddMock.expectedInvocations), m.AddMock.expectedInvocationsOrigin, afterAddCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UserRepoMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UserRepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UserRepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddDone()
}
